name: Enable Auto Merge
on:
  pull_request_target:
  workflow_dispatch:

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: kenhowardpdx/auto-merge-action@v1
      if: ${{ github.actor == 'dependabot[bot]' }}
